version: "3.9"

services:
  database:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - database
      - redis
      - vite
    env_file: .env
    environment:
      - VITE_RUBY_HOST=vite
      - DOCKERIZED=true
      - PGUSER=postgres
  redis:
    image: redis
    ports: 
      - 6379:6379
    volumes:
      - price_tracker_redis_data:/data
  sidekiq:
    build: .
    volumes:
      - .:/price-tracker
    environment:
      RAILS_ENV: development
    depends_on:
      - database
      - redis
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoint-sidekiq.sh
  vite:
    build: .
    entrypoint: ./docker/vite
    environment:
      DEBUG: '*vite*'
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
    ports:
      - "3036:3036"
    volumes:
      - .:/price-tracker

volumes:
  db_data:
  price_tracker_redis_data:
  price_tracker_bundler: